#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

enum class ProcessPriority : uint8_t {
  Idle = 0,
  BelowNormal = 1,
  Normal = 2,
  AboveNormal = 3,
  High = 4,
  Realtime = 5,
};

enum class TimerStrategy : uint8_t {
  SpinSleep = 0,
  StdSleep = 1,
  SpinWait = 2,
};

} // namespace autd3::native_methods
