#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdint>

namespace autd3::native_methods {

/// The process priority. See
/// [`ProcessPriorityClass`](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.processpriorityclass?view=net-8.0#system-diagnostics-processpriorityclass-idle)
/// for more information.
enum class ProcessPriority : uint8_t {
  Idle = 0,
  BelowNormal = 1,
  Normal = 2,
  AboveNormal = 3,
  High = 4,
  Realtime = 5,
};

/// The status of the EtherCAT slave.
enum class Status : uint8_t {
  /// The slave is in SAFE_OP + ERROR.
  Error = 0,
  /// The slave is lost.
  Lost = 1,
  /// The slave is in SAFE_OP.
  StateChanged = 2,
};

}  // namespace autd3::native_methods
