name: pr

on:
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changed-files:
    name: changed-files
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changed-files-yaml.outputs.src_any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - id: changed-files-yaml
        uses: tj-actions/changed-files@v46
        with:
          files_yaml: |
            src:
              - CMakeLists.txt
              - '**/CMakeLists.txt'
              - '**/*.hpp'
              - '**/*.cpp'

  test:
    needs: changed-files
    if: ${{ needs.changed-files.outputs.src == 'true' }}
    name: test-on-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-build
      - run: |
          cargo make build
          cargo make test

  all-tests-passed:
    if: ${{ always() }}
    name: all-tests-passed
    runs-on: ubuntu-latest
    needs: test
    steps:
      - if: ${{ needs.test.result == 'failure' || needs.test.result == 'cancelled' }}
        run: exit 1
